name: 'Julia downgrade compat entries'
description: 'Restrict the compat entries in Project.toml so that only the oldest versions are installed.'
inputs:
  skip:
    description: 'Comma-separated list of packages to not downgrade.'
    default: ''
  strict:
    description: 'true, false or v0. Default: v0.'
    default: 'false'
runs:
  using: "composite"
  steps:
    - run: julia downgrade.jl "${{ join(inputs.skip) }}" "${{ inputs.strict }}"
      shell: bash
